version: '3.0'
services:
  database:
    image: postgres
    ports:
      - "5438:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=school-management
    networks:
      - student-api-network

  admin:
    image: dpage/pgadmin4
    ports:
      - "8981:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@school.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    networks:
      - student-api-network

networks:
  student-api-network: